### ISSUE TITLE
PhpParser non trouvé

### ISSUE THREAD

**Issue by vjacquemin-sli** [owebia/module-shipping-free#1]
Bonjour,

J'ai installé vos modules ShippingCore et ShippingFree sur Magento 2 et je me retrouve avec une erreur dans le debug:

Carrier[owsh1].getConfig - Error - Source class "\Magento\TestFramework\Integrity\Library\PhpParser\Parser" for "Magento\TestFramework\Integrity\Library\PhpParser\ParserFactory" generation does not exist.

Je ne parviens pas à voir Owebia dans les shipping methods en suivant votre exemple

Effectivement, sur mon IDE, il semblerait que PhpParser soit utilisé, et mon IDE non plus ne parvient pas à refaire le lien vers la bonne classe non plus.

Y a t'il un autre module à installer?

Merci

V.J.

**Comment by owebia** [comment]
Bonjour,

Avez-vous utilisé composer pour installer les dépendances ?

Cordialement,
A.L.

**Comment by owebia** [comment]
Voilà la commande pour installer le module via composer :
```shell
composer require owebia/module-shipping-core:@dev owebia/module-shipping-free:@dev
```

A.L.
