### ISSUE TITLE
Defining a table error

### ISSUE THREAD

**Issue by mengento** [owebia/module-shipping-free#2]
Hello
My product weight is 200
Owebia Shipping Configuration:
`addMethod('id_011', [
    'title'      => "Shipping",
    'price'      => array_reduce([ [100, 5.30], [200, 6.50], [300, 7.50]  ], function ($carry, $item) {
                        global $request;
                        if (isset($carry)) return $carry;
                        if (isset($item[0]) && ($request->package_weight <= $item[0] || $item[0] == '*')) {
                            $carry = $item[1];
                        }
                        return $carry;
                    }),
]);`

But Estimate Shipping is 7.50
![2016-03-02t09-18-05 333z](https://cloud.githubusercontent.com/assets/10205547/13455939/672b6b30-e09b-11e5-8c2e-c649ddac5ef3.png)

**Comment by owebia** [comment]
@mengento Thank you for your feedback. The issue has been fixed in owebia/module-shipping-core
