### ISSUE TITLE
Source class error in Carrier::getConfig

### ISSUE THREAD

**Issue by redelschaap** [owebia/module-shipping-free#3]
I can't get my shipping methods to work. In the debug I see the following error:

```
Carrier[owsh1].getConfig - Error - Source class "\PhpParser\Parser" for "PhpParser\ParserFactory" generation does not exist.
```

In `Owebia/ShippingCore/Helper/Config.php` I see the `use PhpParser\ParserFactory;` statement. My IDE can't resolve that class, so my guess is that it just isn't available.

There is however a class `ParserFactory` available at `vendor/magento/magento2-base/dev/tests/static/framework/Magento/TestFramework/Integrity/Library/PhpParser/ParserFactory.php`, but when I replace `use PhpParser\ParserFactory;` with `use \Magento\TestFramework\Integrity\Library\PhpParser\ParserFactory;`, I get the error 
```
Carrier[owsh1].getConfig - Error - Source class "\Magento\TestFramework\Integrity\Library\PhpParser\Parser" for "Magento\TestFramework\Integrity\Library\PhpParser\ParserFactory" generation does not exist.
```

**Comment by owebia** [comment]
Did you make a manual installation ?
Composer installs dependencies but if you don't use it, it is more complicated to install the extension.

- owebia/module-shipping-free requires owebia/module-shipping-core
- owebia/module-shipping-core requires nikic/php-parser

Make a manual installation of owebia/module-shipping-free and owebia/module-shipping-core is easy (put files in app/code/Owebia/ShippingFree and app/code/Owebia/ShippingCore) but nikic/php-parser as an autoloader which must be included (composer manages this).

If the problem only occurs in your IDE, you have to add libraries path (in this case, it is in vendor/nikic/php-parser)

**Comment by redelschaap** [comment]
We did install the extension manually because we got a dependency error at that time.

We removed the extension from our store and reinstalled it. This time it installed via composer and it downloaded the parser package. Thanks for your help!
