### ISSUE TITLE
Compatibility with magento 2.1

### ISSUE THREAD

**Issue by valibus** [owebia/module-shipping-free#5]
Can you add the magento 2.1 compatibility please ?

`"magento/module-variable": "100.1.0"`

**Comment by Yonn-Trimoreau** [comment]
+1

**Comment by owebia** [comment]
Fixed with issue owebia/module-shipping-core#7

**Comment by valibus** [comment]
problem with update
 

> Problem 1
>     - owebia/module-shipping-free dev-master requires owebia/module-shipping-core ^1.0 -> no matching package found.
>     - owebia/module-shipping-free dev-master requires owebia/module-shipping-core ^1.0 -> no matching package found.
>     - Installation request for owebia/module-shipping-free dev-master -> satisfiable by owebia/module-shipping-free[dev-master].

in composer.json the require contains :
```
 "owebia/module-shipping-core": "dev-master",
    "owebia/module-shipping-free": "dev-master"
```
Is there a problem in shipping free? only shipping core has been fixed?

**Comment by owebia** [comment]
@valibus : you have probably a composer cache problem because both shipping-core and shipping-free have been updated (you can check on github and on packagist.org)
